# Generated by Django 3.2.9 on 2021-11-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
